---

x-base: &base
  restart: unless-stopped
  logging:
    driver: "loki"
    options:
      mode: non-blocking
      loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
      loki-retries: "5"

x-cardano_node_10_5_1: &cardano_node_10_5_1
  image: ${testnet}-10.5.1:latest
  build:
    context: "../../"
    dockerfile: "cardano-node/Dockerfile.source"
    args:
      CARDANO_NODE_REF: "10.5.1"

x-cardano_node_10_5_4: &cardano_node_10_5_4
  image: ${testnet}-10.5.4:latest
  build:
    context: "../../"
    dockerfile: "cardano-node/Dockerfile.source"
    args:
      CARDANO_NODE_REF: "10.5.4"

x-env: &env
  POOL_ID: "0" # Placeholder required for override
  SYSTEM_START: ${SYSTEM_START:-}

services:
  p1:
    <<: [*base, *cardano_node_10_5_4]
    container_name: p1
    hostname: p1.example
    volumes:
      - p1:/opt/cardano-node/data
      - synth:/opt/synth:ro
    environment:
      <<: *env
      POOL_ID: "1"
    profiles: [build, core, pools]

  p2:
    <<: [*base, *cardano_node_10_5_4]
    container_name: p2
    hostname: p2.example
    volumes:
      - p2:/opt/cardano-node/data
      - synth:/opt/synth:ro
    environment:
      <<: *env
      POOL_ID: "2"
      PEER_SHARING: "false"
    profiles: [build, core, pools]

  p3:
    <<: [*base, *cardano_node_10_5_4]
    container_name: p3
    hostname: p3.example
    volumes:
      - p3:/opt/cardano-node/data
      - synth:/opt/synth:ro
    environment:
      <<: *env
      POOL_ID: "3"
    profiles: [build, core, pools]

  a1:
    image: amaru_${testnet}:latest
    container_name: a1
    hostname: a1.example
    volumes:
      - a1:/opt/
      - synth:/opt/synth:ro
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    logging:
      driver: "loki"
      options:
        mode: non-blocking
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-retries: "5"
    build:
      context: "../../"
      dockerfile: "amaru/Dockerfile.source"
    environment:
      POOL_ID: "1"
      RELAY_ID: "1"
      TYPE: "client"
      SYSTEM_START: ${SYSTEM_START:-}
    profiles: [build, core]

  a2:
    image: amaru_${testnet}:latest
    container_name: a2
    hostname: a2.example
    volumes:
      - a2:/opt/
      - synth:/opt/synth:ro
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    logging:
      driver: "loki"
      options:
        mode: non-blocking
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-retries: "5"
    build:
      context: "../../"
      dockerfile: "amaru/Dockerfile.source"
    environment:
      POOL_ID: "2"
      RELAY_ID: "2"
      TYPE: "client"
      PEER_HOST: a1
      SYSTEM_START: ${SYSTEM_START:-}
    profiles: [build, core]

  # DNS Server
  ns:
    image: coredns/coredns:1.14.1
    container_name: ns
    hostname: ns.example
    restart: unless-stopped
    command: -conf /etc/coredns/corefile
    volumes:
      - ./coredns:/etc/coredns # Mount custom corefile
    profiles: [build, core]

  sidecar:
    image: ${testnet}_sidecar:latest
    container_name: sidecar
    hostname: sidecar.example
    restart: unless-stopped
    build:
      context: "../../"
      dockerfile: "sidecar/Dockerfile"
    environment:
      POOLS: "3"

  synth:
    image: ${testnet}_db-synthesizer:latest
    container_name: synth
    restart: no
    environment:
      SYSTEM_START: ${SYSTEM_START:-}
      PRE_EPOCHS: ${PRE_EPOCHS:-4}
      MAX_POOLS: ${MAX_POOLS:-2}
    volumes:
      - synth:/opt/cardano-node/data
    build:
      context: "../../"
      dockerfile: "db-synthesizer/Dockerfile"
    profiles: [build, core, mgmt]

  # Client 1
  # Used by cardano-db-sync
  c1:
    <<: [*base, *cardano_node_10_5_4]
    container_name: c1
    hostname: c1.example
    volumes:
      - c1:/opt/cardano-node
      - synth:/opt/synth:ro
    environment:
      POOL_ID: "1"
      TYPE: "client"
      SYSTEM_START: ${SYSTEM_START:-}
    profiles: [build, core]

  # TX generator 1
  c2:
    <<: [*base, *cardano_node_10_5_4]
    container_name: c2
    hostname: c2.example
    volumes:
      - c2:/opt/cardano-node
      - synth:/opt/synth:ro
    environment:
      POOL_ID: "1"
      TYPE: "txg"
      TPS: "1"
      TX_GEN_MODE: "plain"
      UTXOHD: "false"
      SYSTEM_START: ${SYSTEM_START:-}
    profiles: [build, optional]

  # PostgreSQL Database
  db:
    image: postgresql:latest
    container_name: db
    hostname: db.example
    restart: unless-stopped
    volumes:
      - db:/opt/postgresql
    build:
      context: "../../"
      dockerfile: "postgresql/Dockerfile"
    profiles: [build, core]

  dbsync:
    image: cardano-db-sync:latest
    container_name: dbsync
    hostname: dbsync.example
    restart: unless-stopped
    volumes:
      - dbsync:/opt/cardano-db-sync
      - c1:/opt/cardano-node
    environment:
      DB_HOST: "db.example"
    build:
      context: "../../"
      dockerfile: "cardano-db-sync/Dockerfile.binary"
    depends_on:
      db:
        condition: service_started
    profiles: [build, core]

  blockfrost:
    image: blockfrost:latest
    container_name: blockfrost
    hostname: blockfrost.example
    restart: unless-stopped
    volumes:
      - c1:/opt/cardano-node
    environment:
      DB_HOST: "db.example"
    build:
      context: "../../"
      dockerfile: "blockfrost/Dockerfile"
    profiles: [build, optional]

  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    hostname: prometheus.example
    restart: unless-stopped
    volumes:
      - prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      blackbox:
        condition: service_started
    profiles: [build, core]

  blackbox:
    image: quay.io/prometheus/blackbox-exporter:v0.28.0
    container_name: blackbox
    hostname: blackbox.example
    restart: unless-stopped
    command: --config.file=/etc/blackbox_exporter/blackbox.yml
    volumes:
      - ../../blackbox:/etc/blackbox_exporter/
    cap_add:
      - NET_ADMIN
      - NET_RAW
    profiles: [build, core]

  loki:
    image: grafana/loki:3.6.4
    container_name: loki
    hostname: loki.example
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - loki:/loki
    profiles: [build, core]

  grafana:
    image: grafana/grafana:12.3.1
    container_name: grafana
    hostname: grafana.example
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
      - ../../grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: cardano
      GF_SECURITY_ADMIN_PASSWORD: cardano
    profiles: [build, core]

  jaeger:
    image: jaegertracing/jaeger:2.14.1
    container_name: jaeger
    hostname: jaeger.example
    restart: unless-stopped
    volumes:
      - ../../jaeger/jaeger-ui.json:/etc/jaeger/jaeger-ui.json
      - ../../jaeger/jaeger.yml:/etc/jaeger/config.yml
    command: ["--config", "/etc/jaeger/config.yml"]
    profiles: [build, core]

  otlp:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otlp
    hostname: otlp.example
    volumes:
      - ../../opentelemetry/otlp-collector.yml:/etc/otlp-collector.yml
    command: ["--config", "/etc/otlp-collector.yml"]
    profiles: [build, core]

volumes:
  p1:
  p2:
  p3:
  a1:
  a2:
  c1:
  c2:
  db:
  dbsync:
  prometheus:
  loki:
  grafana:
  synth:
